#include "stm32f4xx_hal.h"
#include "bsp_led.h"
#include <board.h>



void led_init(void)
{
	uint16_t i = 0;
	
	GPIO_InitTypeDef GPIO_InitStruct = {0};	

	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();
	__HAL_RCC_GPIOD_CLK_ENABLE();
	__HAL_RCC_GPIOE_CLK_ENABLE();

	/*
	PA6->FLASH_TRIGER
	PA1->ALARM_CONTROL
	*/
	GPIO_InitStruct.Pin = FLASH_TRIGER_GPIO_PIN | ALARM_CONTROL_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);	
	
	/*
	PB8->TEMP_INIT
	*/
	GPIO_InitStruct.Pin = TEMP_INIT_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(TEMP_INIT_GPIO, &GPIO_InitStruct);	
	
	
	/*
	LM92 :	PD8 PD9
	MAX5477: PD10 PD11 PD12 
	WP: PD13
	*/
	GPIO_InitStruct.Pin = LM92CIM_AA1_GPIO_PIN | LM92CIM_AA0_GPIO_PIN | MAX5477_A0_GPIO_PIN | MAX5477_A1_GPIO_PIN | MAX5477_A2_GPIO_PIN | MAX5477_WP_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);	
	
	/*
		X9C103
	*/
	GPIO_InitStruct.Pin = X9C103_INC_GPIO_PIN | X9C103_UD_GPIO_PIN | X9C103_CS_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLUP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);	
	
	//WP
	HAL_GPIO_WritePin(GPIOD, MAX5477_WP_GPIO_PIN, GPIO_PIN_RESET);

	//LM92
	HAL_GPIO_WritePin(GPIOD, LM92CIM_AA1_GPIO_PIN | LM92CIM_AA0_GPIO_PIN, GPIO_PIN_RESET);
	
	//MAX5477
	HAL_GPIO_WritePin(GPIOD, MAX5477_A1_GPIO_PIN | MAX5477_A2_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOD, MAX5477_A0_GPIO_PIN, GPIO_PIN_SET);
	//001
	HAL_GPIO_WritePin(GPIOA, FLASH_TRIGER_GPIO_PIN | ALARM_CONTROL_GPIO_PIN, GPIO_PIN_RESET);
	
	////X9C103
	HAL_GPIO_WritePin(GPIOE, X9C103_INC_GPIO_PIN | X9C103_UD_GPIO_PIN | X9C103_CS_GPIO_PIN, GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(GPIOE, X9C103_CS_GPIO_PIN, GPIO_PIN_SET);
	
	for(i = 0; i < 200; i++)
	{
		HAL_GPIO_WritePin(GPIOE, X9C103_INC_GPIO_PIN, GPIO_PIN_SET);
		//Delay1(0xffe);
		rt_thread_mdelay(1);		
		HAL_GPIO_WritePin(GPIOE, X9C103_INC_GPIO_PIN, GPIO_PIN_RESET);
	}
	
	HAL_GPIO_WritePin(GPIOE, X9C103_CS_GPIO_PIN, GPIO_PIN_RESET);

	for( i = 0; i < 70; i++)
	{
		HAL_GPIO_WritePin(GPIOE, X9C103_INC_GPIO_PIN, GPIO_PIN_SET);
		//Delay1(0xffe); 
		rt_thread_mdelay(1);
		HAL_GPIO_WritePin(GPIOE, X9C103_INC_GPIO_PIN, GPIO_PIN_RESET);
	}	
}